name: release-nightly

on:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  release-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: gitea
      DOCKER_LATEST: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Liteyuki Harbor
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: basic
          platforms: |
            linux/amd64
#            linux/arm64
          push: true
          tags: |
            reg.liteyuki.icu/comp/liteyuki-runner:latest

      - name: Build and push dind
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: dind
          platforms: |
            linux/amd64
#            linux/arm64
          push: true
          tags: |
            reg.liteyuki.icu/comp/liteyuki-runner:latest-dind

      - name: Build and push dind-rootless
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: dind-rootless
          platforms: |
            linux/amd64
#            linux/arm64
          push: true
          tags: |
            reg.liteyuki.icu/comp/liteyuki-runner:latest-dind-rootless
